name: Build Webpage
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./vault

      - name: Build page
        run: |
          set +e
          mkdir -p ./.output

          docker run --rm -v ./vault:/vault -v ./.output:/output KosmosisDire/obsidian-webpage-export:latest >> ./.log.txt

          cat ./.log.txt

          if [ $? -eq 137 ]; then
            exit 0
            echo "output=./.output" >> $GITHUB_OUTPUT
          fi

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4